"""Reporters: console, JSON, Markdown, SARIF, and a self-contained HTML page."""

import json
import re
from dataclasses import asdict
from pathlib import Path
from typing import Dict, List

from scanner.schema import SEVERITY_ORDER, Finding


def severity_counts(findings: List[Finding]) -> Dict[str, int]:
    counts = {sev: 0 for sev in SEVERITY_ORDER}
    for f in findings:
        counts[f.severity] = counts.get(f.severity, 0) + 1
    return counts


def _summary_line(findings: List[Finding]) -> str:
    counts = severity_counts(findings)
    parts = [f"{sev}: {counts.get(sev, 0)}" for sev in SEVERITY_ORDER]
    return " | ".join(parts) + f"  (total {len(findings)})"


def language_counts(findings: List[Finding]) -> Dict[str, int]:
    counts: Dict[str, int] = {}
    for f in findings:
        lang = f.language or "Unknown"
        counts[lang] = counts.get(lang, 0) + 1
    return counts


def _language_line(findings: List[Finding]) -> str:
    counts = language_counts(findings)
    ordered = sorted(counts.items(), key=lambda kv: (-kv[1], kv[0]))
    return "Languages: " + ", ".join(f"{lang} ({n})" for lang, n in ordered)


def print_findings(findings: List[Finding], verbose: bool = False) -> None:
    if not findings:
        print("No findings detected.")
        return

    num_w = max(2, len(str(len(findings))))
    sev_w = max(len("SEVERITY"), max(len(f.severity) for f in findings))
    loc_w = max(len("LOCATION"), max(len(f"{f.file}:{f.line}") for f in findings))

    # Numbered table laid out like the example in the brief:
    #   1  HIGH  src/config.js:12  Possible hardcoded secret
    print(f"{'#':>{num_w}}  {'SEVERITY':<{sev_w}}  {'LOCATION':<{loc_w}}  SHORT EXPLANATION")
    print(f"{'-' * num_w}  {'-' * sev_w}  {'-' * loc_w}  {'-' * len('SHORT EXPLANATION')}")
    for i, f in enumerate(findings, start=1):
        loc = f"{f.file}:{f.line}"
        print(f"{i:>{num_w}}  {f.severity:<{sev_w}}  {loc:<{loc_w}}  {f.message}")
        if verbose:
            meta = [f.rule]
            if f.cwe:
                meta.append(f.cwe)
            meta.append(f"conf {f.confidence:.2f}")
            if f.remediation:
                meta.append(f"fix: {f.remediation}")
            print(f"{' ' * (num_w + 2)}{' | '.join(meta)}")

    print()
    print(_summary_line(findings))
    print(_language_line(findings))


def write_json_report(findings: List[Finding], output_path: Path) -> None:
    payload = {
        "summary": severity_counts(findings),
        "total": len(findings),
        "findings": [asdict(f) for f in findings],
    }
    output_path.write_text(json.dumps(payload, indent=2), encoding="utf-8")


def write_markdown_report(findings: List[Finding], output_path: Path) -> None:
    lines: List[str] = ["# Security Findings", ""]
    lines.append(f"_Generated by Mini Static Findings Scanner._")
    lines.append("")
    lines.append(f"**Summary:** {_summary_line(findings)}")
    lines.append("")
    if findings:
        lines.append(f"**{_language_line(findings)}**")
        lines.append("")

    if not findings:
        lines.append("No findings detected.")
        output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
        return

    counter = 0
    for sev in sorted(SEVERITY_ORDER, key=lambda s: SEVERITY_ORDER[s]):
        group = [f for f in findings if f.severity == sev]
        if not group:
            continue
        lines.append(f"## {sev} ({len(group)})")
        lines.append("")
        for f in group:
            counter += 1
            meta = [f"`{f.file}:{f.line}`"]
            if f.cwe:
                meta.append(f.cwe)
            meta.append(f"confidence {f.confidence:.2f}")
            lines.append(f"**{counter}. {f.rule}**")
            lines.append(f"{' · '.join(meta)}")
            lines.append("")
            lines.append(_oneline(f.message))
            if f.remediation:
                lines.append("")
                lines.append(f"**Fix:** {_oneline(f.remediation)}")
            lines.append("")

    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _oneline(text: str) -> str:
    return " ".join(text.split())


# SARIF 2.1.0, for GitHub code scanning and the VS Code SARIF viewer.

# SARIF carries severity in a "level" field; map our labels onto it.
_SARIF_LEVEL = {"HIGH": "error", "MED": "warning", "LOW": "note"}
# GitHub also wants a numeric "security-severity" (CVSS-like, 0-10).
_SECURITY_SEVERITY = {"HIGH": "8.0", "MED": "5.0", "LOW": "2.0"}


def _slug(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")


def _sarif_rules(findings: List[Finding]) -> List[dict]:
    from scanner.rules import RULES
    meta = {r.name: r for r in RULES}
    rules: List[dict] = []
    seen = set()
    for f in findings:
        if f.rule in seen:
            continue
        seen.add(f.rule)
        rule = meta.get(f.rule)
        cwe = f.cwe or (rule.cwe if rule else None)
        tags = ["security"] + ([cwe] if cwe else [])
        entry = {
            "id": _slug(f.rule),
            "name": f.rule,
            "shortDescription": {"text": rule.description if rule else f.rule},
            "properties": {
                "tags": tags,
                "security-severity": _SECURITY_SEVERITY.get(f.severity, "5.0"),
            },
        }
        if rule and rule.remediation:
            entry["help"] = {"text": rule.remediation}
        rules.append(entry)
    return rules


def _sarif_results(findings: List[Finding]) -> List[dict]:
    results = []
    for f in findings:
        results.append({
            "ruleId": _slug(f.rule),
            "level": _SARIF_LEVEL.get(f.severity, "warning"),
            "message": {"text": f.message},
            "locations": [{
                "physicalLocation": {
                    "artifactLocation": {"uri": f.file},
                    "region": {"startLine": max(1, f.line)},
                }
            }],
            "properties": {
                "severity": f.severity,
                "confidence": f.confidence,
                "cwe": f.cwe,
                "language": f.language,
            },
        })
    return results


def write_sarif_report(findings: List[Finding], output_path: Path) -> None:
    sarif = {
        "$schema": "https://json.schemastore.org/sarif-2.1.0.json",
        "version": "2.1.0",
        "runs": [{
            "tool": {"driver": {
                "name": "Mini Static Findings Scanner",
                "version": "1.0.0",
                "rules": _sarif_rules(findings),
            }},
            "results": _sarif_results(findings),
        }],
    }
    output_path.write_text(json.dumps(sarif, indent=2), encoding="utf-8")


# Self-contained HTML review UI: no server, no dependencies.

_HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Mini Static Findings Scanner</title>
<style>
:root{--high:#e5484d;--med:#f5a623;--low:#3b82f6;--fix:#46c08d;--bg:#0d0f14;--card:#151922;--line:#222734;--mut:#8b93a0;}
*{box-sizing:border-box;}
body{margin:0;font-family:-apple-system,Segoe UI,Roboto,sans-serif;color:#e8eaed;
  background:radial-gradient(1200px 600px at 50% -200px,#1b2030,#0d0f14);min-height:100vh;}
.wrap{max-width:1180px;margin:0 auto;padding:0 20px 48px;}
header{text-align:center;padding:40px 16px 8px;}
h1{margin:0;font-size:26px;font-weight:700;letter-spacing:-.02em;
  background:linear-gradient(90deg,#fff,#9fb4ff);-webkit-background-clip:text;background-clip:text;color:transparent;}
.sub{color:var(--mut);font-size:14px;margin-top:6px;}
.counts{margin-top:18px;display:flex;gap:10px;flex-wrap:wrap;justify-content:center;}
.pill{padding:6px 16px;border-radius:999px;font-size:13px;font-weight:600;cursor:pointer;
  border:1px solid #2c313c;background:#11141b;user-select:none;transition:.15s;}
.pill.HIGH{color:var(--high);} .pill.MED{color:var(--med);} .pill.LOW{color:var(--low);}
.pill:hover{transform:translateY(-1px);}
.pill.off{opacity:.32;}
.toolbar{margin:22px auto 14px;display:flex;gap:12px;align-items:center;justify-content:center;flex-wrap:wrap;}
input[type=search],select{background:#11141b;border:1px solid #2c313c;color:#e8eaed;padding:9px 12px;border-radius:10px;font-size:13px;}
input[type=search]{width:min(420px,70vw);}
input[type=search]:focus,select:focus{outline:none;border-color:#3a4a7a;}
.card{background:var(--card);border:1px solid var(--line);border-radius:14px;overflow:hidden;box-shadow:0 12px 40px rgba(0,0,0,.35);}
table{width:100%;border-collapse:collapse;font-size:13px;}
th,td{text-align:left;padding:11px 16px;border-bottom:1px solid var(--line);vertical-align:top;}
th{color:var(--mut);font-weight:600;font-size:11px;text-transform:uppercase;letter-spacing:.05em;
  position:sticky;top:0;background:#10141c;backdrop-filter:blur(6px);}
tr.row{cursor:pointer;}
tr.row:hover{background:#1a1f2b;}
tr.row.HIGH td:first-child{box-shadow:inset 3px 0 var(--high);}
tr.row.MED td:first-child{box-shadow:inset 3px 0 var(--med);}
tr.row.LOW td:first-child{box-shadow:inset 3px 0 var(--low);}
.badge{display:inline-block;padding:3px 9px;border-radius:6px;font-size:11px;font-weight:700;}
.badge.HIGH{background:rgba(229,72,77,.16);color:var(--high);}
.badge.MED{background:rgba(245,166,35,.16);color:var(--med);}
.badge.LOW{background:rgba(59,130,246,.16);color:var(--low);}
.loc{font-family:ui-monospace,Consolas,monospace;color:#cbd2dc;white-space:nowrap;}
.desc{font-weight:500;}
.rem{margin-top:5px;font-size:12px;color:var(--fix);display:flex;gap:6px;align-items:flex-start;}
.rem b{font-weight:600;opacity:.85;}
.caret{color:var(--mut);font-size:11px;}
.detail td{background:#0f131b;}
.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:10px;margin-bottom:10px;}
.kv{background:#141925;border:1px solid var(--line);border-radius:8px;padding:8px 10px;}
.kv .k{color:var(--mut);font-size:10.5px;text-transform:uppercase;letter-spacing:.04em;}
.kv .v{margin-top:3px;font-size:13px;word-break:break-word;}
.fixbox{background:rgba(70,192,141,.08);border:1px solid rgba(70,192,141,.3);border-radius:8px;padding:10px 12px;}
.fixbox .k{color:var(--fix);font-weight:700;font-size:12px;}
.fixbox .v{margin-top:4px;color:#cdeede;font-size:13px;}
.muted{color:var(--mut);font-size:13px;}
footer{text-align:center;padding:22px;color:#5b6270;font-size:12px;}
.empty{padding:48px;text-align:center;color:var(--mut);display:none;}
</style></head><body><div class="wrap">
<header><h1>Mini Static Findings Scanner</h1>
<div class="sub" id="sub"></div><div class="counts" id="counts"></div></header>
<div class="toolbar">
<input type="search" id="q" placeholder="Search file, rule, or description...">
<select id="lang"><option value="">All languages</option></select>
<span class="muted" id="shown"></span></div>
<div class="card"><table>
<thead><tr><th>#</th><th>Severity</th><th>File path</th><th>Line</th><th>Rule name</th><th>Short explanation &amp; remediation</th></tr></thead>
<tbody id="rows"></tbody></table>
<div class="empty" id="empty">No findings match your filters.</div></div>
<footer>Generated locally - no data leaves your machine. Click any row for full details.</footer>
</div>
<script>
const DATA=__DATA__;
const sevState={HIGH:true,MED:true,LOW:true};
const order={HIGH:0,MED:1,LOW:2};
const $=id=>document.getElementById(id);
$('sub').textContent=DATA.length+' findings';
[...new Set(DATA.map(d=>d.language).filter(Boolean))].sort().forEach(l=>{
  const o=document.createElement('option');o.value=l;o.textContent=l;$('lang').appendChild(o);});
function counts(){const c={HIGH:0,MED:0,LOW:0};DATA.forEach(d=>c[d.severity]=(c[d.severity]||0)+1);return c;}
function renderCounts(){const c=counts();$('counts').innerHTML='';
  ['HIGH','MED','LOW'].forEach(s=>{const e=document.createElement('span');
    e.className='pill '+s+(sevState[s]?'':' off');e.textContent=s+' '+(c[s]||0);
    e.onclick=()=>{sevState[s]=!sevState[s];renderCounts();render();};$('counts').appendChild(e);});}
function esc(s){return (s==null?'':String(s)).replace(/[&<>]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[m]));}
function render(){
  const q=$('q').value.toLowerCase(),lf=$('lang').value;
  let list=DATA.filter(d=>sevState[d.severity]&&(!lf||d.language===lf)&&
    (!q||(d.file+d.rule+d.message+(d.remediation||'')).toLowerCase().includes(q)));
  list.sort((a,b)=>(order[a.severity]-order[b.severity])||(b.confidence-a.confidence));
  $('rows').innerHTML='';
  list.forEach((d,i)=>{
    const tr=document.createElement('tr');tr.className='row '+d.severity;
    const rem=d.remediation?'<div class="rem"><b>Fix:</b><span>'+esc(d.remediation)+'</span></div>':'';
    tr.innerHTML='<td>'+(i+1)+' <span class="caret">&#9656;</span></td>'+
      '<td><span class="badge '+d.severity+'">'+d.severity+'</span></td>'+
      '<td class="loc">'+esc(d.file)+'</td><td class="loc">'+d.line+'</td>'+
      '<td>'+esc(d.rule)+'</td>'+
      '<td><div class="desc">'+esc(d.message)+'</div>'+rem+'</td>';
    const det=document.createElement('tr');det.className='detail';det.style.display='none';
    det.innerHTML='<td></td><td colspan="5">'+
      '<div class="grid">'+
        '<div class="kv"><div class="k">CWE</div><div class="v">'+esc(d.cwe||'-')+'</div></div>'+
        '<div class="kv"><div class="k">Confidence</div><div class="v">'+d.confidence+'</div></div>'+
        '<div class="kv"><div class="k">Language</div><div class="v">'+esc(d.language||'-')+'</div></div>'+
        '<div class="kv"><div class="k">Category</div><div class="v">'+esc(d.category||'-')+'</div></div>'+
        '<div class="kv"><div class="k">Evidence</div><div class="v"><code>'+esc(d.evidence||'-')+'</code></div></div>'+
      '</div>'+
      '<div class="fixbox"><div class="k">Remediation</div><div class="v">'+esc(d.remediation||'-')+'</div></div>'+
      '</td>';
    tr.onclick=()=>{det.style.display=det.style.display==='none'?'':'none';};
    $('rows').appendChild(tr);$('rows').appendChild(det);});
  $('shown').textContent=list.length+' shown';
  $('empty').style.display=list.length?'none':'block';}
$('q').oninput=render;$('lang').onchange=render;renderCounts();render();
</script></body></html>
"""


def write_html_report(findings: List[Finding], output_path: Path) -> None:
    data = [asdict(f) for f in findings]
    payload = json.dumps(data).replace("</", "<\\/")  # avoid closing the <script> early
    output_path.write_text(_HTML_TEMPLATE.replace("__DATA__", payload), encoding="utf-8")
