"""Detection rules.

Each rule owns its severity; any match it produces inherits that severity.
Rules combine a regex with optional context keywords and a list of validators
(see validators.py) that suppress false positives or adjust confidence.
"""

from scanner.schema import HIGH, LOW, MED, Rule

IGNORE_DIRS = {
    ".git",
    "node_modules",
    "dist",
    "build",
    "__pycache__",
    ".venv",
    "venv",
    ".tox",
    ".mypy_cache",
    ".pytest_cache",
    "vendor",
    "coverage",
}

TEXT_EXTENSIONS = {
    ".py", ".js", ".ts", ".jsx", ".tsx", ".java", ".go", ".rb", ".php",
    ".cs", ".cpp", ".c", ".h", ".html", ".css", ".json", ".yaml", ".yml",
    ".env", ".md", ".txt", ".sh", ".ps1", ".xml", ".ini", ".conf", ".cfg",
    ".properties", ".toml", ".pem", ".key", ".crt", ".cer",
}

RULES = [
    Rule(
        name="Hardcoded Secret",
        description="Possible hardcoded secret or credential found",
        severity=HIGH,
        category="Secrets",
        detection_type="regex",
        cwe="CWE-798",
        patterns=[
            r"(?i)\b(api[_-]?key|secret|token|password|passwd|credential|access[_-]?key)\b\s*[:=]\s*['\"][^'\"]{6,}['\"]",
            r"(?i)\b(AWS_SECRET_ACCESS_KEY|AWS_ACCESS_KEY_ID|GITHUB_TOKEN)\b\s*[:=]\s*['\"]?[^\s'\"]+",
        ],
        validators=["env_reference", "placeholder", "secret_prefix", "entropy_charset", "in_comment", "test_path"],
        confidence_base=0.55,
        remediation="Move secrets to environment variables or a managed secrets vault and rotate exposed values.",
    ),
    Rule(
        name="Private Key Exposure",
        description="Private key material detected",
        severity=HIGH,
        category="Secrets",
        detection_type="regex",
        cwe="CWE-321",
        patterns=[
            r"-----BEGIN (RSA |EC |DSA |OPENSSH |PGP |)?PRIVATE KEY-----",
        ],
        validators=["test_path"],
        confidence_base=0.95,
        remediation="Remove private keys from source control and rotate the exposed key material.",
    ),
    Rule(
        name="High Entropy Secret Context",
        description="Long high-entropy value near a secret-related keyword",
        severity=HIGH,
        category="Secrets",
        detection_type="entropy_context",
        cwe="CWE-798",
        patterns=[r"[A-Za-z0-9_\-+/=]{32,}"],
        entropy_threshold=4.2,
        validators=["env_reference", "placeholder", "test_path"],
        confidence_base=0.6,
        remediation="Review whether the value is a credential, token, or key; move real secrets to a vault.",
    ),
    Rule(
        name="Dangerous Code Execution",
        description="Dangerous dynamic code execution function detected",
        severity=HIGH,
        category="Code Execution",
        detection_type="regex",
        cwe="CWE-95",
        patterns=[
            r"\beval\s*\(",
            r"\bexec\s*\(",
            r"subprocess\.\w+\([^)]*shell\s*=\s*True",
            r"\bos\.system\s*\(",
            r"child_process\.(exec|execSync)\s*\(",
        ],
        validators=["code_context", "test_path"],
        confidence_base=0.8,
        remediation="Avoid dynamic execution; if unavoidable, strictly validate and constrain inputs.",
    ),
    Rule(
        name="Insecure Deserialization",
        description="Unsafe deserialization of untrusted data",
        severity=HIGH,
        category="Code Execution",
        detection_type="regex",
        cwe="CWE-502",
        patterns=[
            r"\b(pickle|cPickle|_pickle)\.loads?\s*\(",
            r"\bmarshal\.loads?\s*\(",
            r"\byaml\.load\s*\(",
        ],
        negative_keywords=["SafeLoader", "safe_load"],
        validators=["code_context", "test_path"],
        confidence_base=0.65,
        remediation="Use safe deserialization (e.g. yaml.safe_load, json) and never deserialize untrusted input.",
    ),
    Rule(
        name="Disabled TLS Verification",
        description="TLS/certificate verification appears disabled",
        severity=HIGH,
        category="Transport Security",
        detection_type="regex",
        cwe="CWE-295",
        patterns=[
            r"verify\s*=\s*False",
            r"rejectUnauthorized\s*:\s*false",
            r"InsecureSkipVerify\s*:\s*true",
            r"ssl\._create_unverified_context",
            r"CURLOPT_SSL_VERIFY(PEER|HOST)\s*,\s*(0|false)",
        ],
        validators=["code_context", "test_path"],
        confidence_base=0.85,
        remediation="Enable certificate verification; trust only valid CAs.",
    ),
    Rule(
        name="SQL Injection Risk",
        description="SQL query appears built from string concatenation or interpolation",
        severity=HIGH,
        category="Input Validation",
        detection_type="regex",
        cwe="CWE-89",
        patterns=[
            r"(?i)(SELECT|INSERT|UPDATE|DELETE|DROP)\s+.+['\"]\s*\+\s*\w",
            r"(?i)(execute|query)\s*\(\s*f['\"].*(SELECT|INSERT|UPDATE|DELETE)",
            r"(?i)(execute|query)\s*\([^)]*%\s*\(",
        ],
        validators=["code_context", "test_path"],
        confidence_base=0.6,
        remediation="Use parameterized queries / prepared statements instead of string building.",
    ),
    Rule(
        name="Weak Cryptography",
        description="Weak or broken cryptographic algorithm used in a security context",
        severity=MED,
        category="Cryptography",
        detection_type="regex",
        cwe="CWE-327",
        patterns=[
            r"(?i)hashlib\.(md5|sha1)\s*\(",
            r"(?i)createHash\s*\(\s*['\"](md5|sha1)['\"]",
            r"(?i)\b(md5|sha1)\b",
            r"(?i)\b(DES|RC4|ECB)\b",
        ],
        context_keywords=["password", "passwd", "secret", "token", "key", "sign",
                          "hash", "crypt", "auth", "hmac", "salt"],
        context_window=2,
        validators=["code_context", "test_path"],
        confidence_base=0.5,
        remediation="Use modern algorithms (SHA-256+, bcrypt/argon2 for passwords, AES-GCM for ciphers).",
    ),
    Rule(
        name="Sensitive Data in Logs",
        description="Secret or credential appears to be written to logs/console",
        severity=MED,
        category="Information Exposure",
        detection_type="regex",
        cwe="CWE-532",
        patterns=[
            r"(?i)(console\.log|print|logging\.\w+|logger\.\w+|System\.out\.print\w*)\s*\(.*\b(password|passwd|secret|token|api[_-]?key|credential)\b",
        ],
        validators=["test_path"],
        confidence_base=0.5,
        remediation="Never log secrets; redact sensitive fields before logging.",
    ),
    Rule(
        name="Path Traversal Risk",
        description="Unsafe file access from user-controlled input",
        severity=HIGH,
        category="Input Validation",
        detection_type="regex",
        cwe="CWE-22",
        patterns=[
            r"send_file\s*\(",
            r"request\.args\.get\s*\(\s*['\"]file['\"]",
            r"open\s*\(\s*[^)]*(request|input|args|params|req\.query)",
        ],
        validators=["code_context", "test_path"],
        confidence_base=0.6,
        remediation="Normalize paths and enforce an allow-listed base directory before file access.",
    ),
    Rule(
        name="Broad CORS Policy",
        description="Broad CORS policy allows requests from any origin",
        severity=MED,
        category="Configuration",
        detection_type="regex",
        cwe="CWE-942",
        patterns=[
            r"Access-Control-Allow-Origin\s*:\s*\*",
            r"cors\s*\(\s*\{\s*origin\s*:\s*['\"]\*['\"]",
            r"origin\s*:\s*['\"]\*['\"]",
        ],
        validators=["in_comment"],
        confidence_base=0.8,
        remediation="Restrict CORS origins to an explicit allow-list of trusted domains.",
    ),
    Rule(
        name="Debug Mode Enabled",
        description="Debug or development mode appears enabled",
        severity=MED,
        category="Configuration",
        detection_type="regex",
        cwe="CWE-489",
        patterns=[
            r"(?i)debug\s*=\s*true",
            r"(?i)debug\s*:\s*true",
            r"(?i)NODE_ENV\s*=\s*['\"]?development",
            r"app\.run\s*\([^)]*debug\s*=\s*True",
        ],
        validators=["code_context", "test_path"],
        confidence_base=0.75,
        remediation="Disable debug/development mode in production builds.",
    ),
    Rule(
        name="Insecure HTTP URL",
        description="Insecure HTTP URL detected instead of HTTPS",
        severity=MED,
        category="Transport Security",
        detection_type="regex",
        cwe="CWE-319",
        patterns=[r"http://[^\s'\")]+"],
        validators=["benign_url", "in_comment", "test_path"],
        confidence_base=0.55,
        remediation="Use HTTPS for network communication.",
    ),
    Rule(
        name="Sensitive File Present",
        description="Sensitive configuration, credential, database, or backup file found",
        severity=MED,
        category="File Exposure",
        detection_type="filename",
        cwe="CWE-552",
        patterns=[
            r"(^|/)\.env(\.|$)",
            r"\.(pem|key|p12|pfx|sql|sqlite|db|bak|old)$",
            r"(^|/)id_rsa$",
        ],
        confidence_base=0.8,
        remediation="Keep sensitive files out of source control and public web roots.",
    ),
    Rule(
        name="Suspicious Security Comment",
        description="Security-related TODO, FIXME, or temporary bypass comment found",
        severity=LOW,
        category="Code Hygiene",
        detection_type="regex",
        cwe="CWE-546",
        patterns=[
            r"(?i)TODO.*security",
            r"(?i)FIXME.*auth",
            r"(?i)temporary bypass",
            r"(?i)(disable|bypass|skip).*(security|auth|validation)",
        ],
        confidence_base=0.7,
        remediation="Resolve security-related temporary comments before release.",
    ),
]
